var CORE_EXXET_ENABLED = true;

var PANTALLA_ENABLED = true;
var FLAG_PANTALLA_ENABLED = "FLAG_PANTALLA_ENABLED";

var CUMPLEMENTO_WEB_1_ENABLED = true;
var FLAG_CUMPLEMENTO_WEB_1_ENABLED = "FLAG_CUMPLEMENTO_WEB_1_ENABLED";

var GAIA_1_ENABLED = true;
var FLAG_GAIA_1_ENABLED = "FLAG_GAIA_1_ENABLED";

var GAIA_2_ENABLED = true;

var DOMINUS_EXXET_ENABLED = true;
var FLAG_DOMINUS_EXXET_ENABLED = "FLAG_DOMINUS_EXXET_ENABLED";

var ARCANA_EXXET_ENABLED = true;
var FLAG_ARCANA_EXXET_ENABLED = "FLAG_ARCANA_EXXET_ENABLED";

var PROMETHEUM_EXXET_ENABLED = true;
var FLAG_PROMETHEUM_EXXET_ENABLED = "FLAG_PROMETHEUM_EXXET_ENABLED";

var LQCCN_1_ENABLED = true;
var CUMPLEMENTO_WEB_2_ENABLED = true;
var CUMPLEMENTO_WEB_3_ENABLED = true;
