var CORE_EXXET_ENABLED = true;

var PANTALLA_ENABLED = true;
var FLAG_PANTALLA_ENABLED = "FLAG_PANTALLA_ENABLED";

var CUMPLEMENTO_WEB_1_ENABLED = true;
var FLAG_CUMPLEMENTO_WEB_1_ENABLED = "FLAG_CUMPLEMENTO_WEB_1_ENABLED";

var GAIA_1_ENABLED = true;
var GAIA_2_ENABLED = true;
var DOMINUS_EXXET_ENABLED = true;
var ARCANA_EXXET_ENABLED = true;
var PROMETHEUM_EXXET_ENABLED = true;
var LQCCN_1_ENABLED = true;
var CUMPLEMENTO_WEB_2_ENABLED = true;
var CUMPLEMENTO_WEB_3_ENABLED = true;
